const fs = require('fs');

const data = `
BLAZE | blaze-double-flex.png | Double bicep flex, big grin | Hype man, energetic, celebratory | Triggers: workout_complete, personal_record, streak_hit | Tone: loud and celebratory | Messages: "YOU DID IT!", "Personal record CRUSHED.", "Keep that fire burning!" | UI: morning dashboard header, chatbot greeting, workout complete screen
IGNITE | ignite-fists-roar.png | Both fists raised, mouth roaring, confetti | Explosive, unstoppable, triumphant | Triggers: major_milestone, level_up, badge_unlocked | Tone: explosive and triumphant | Messages: "LEVEL UP. You are unstoppable.", "Badge earned. The grind pays off.", "Milestone hit. This is just the beginning." | UI: milestone full-screen popup, major achievement notification
DASHER | dasher-cycling.png | Cycling full speed, helmet on, speed lines | Fast, focused, relentless | Triggers: cardio_start, cycling_logged, speed_goal_hit | Tone: urgent and energizing | Messages: "Pedal harder. No coasting today.", "Speed goal hit. Now push past it.", "Cardio mode activated. Let's go." | UI: cardio workout start screen, cycling tracker header
FORGE | forge-pointing.png | Pointing at viewer, serious face | Direct, no-nonsense, tough | Triggers: daily_reminder, challenge_sent, accountability_checkin, error_state, empty_state | Tone: tough love, direct | Messages: "No excuses. Let's go.", "You said today. Today is now.", "Still waiting. The gym isn't going to itself." | UI: push notification reminder, empty state screens, error screens, challenge screen, chatbot error state
TITAN | titan-thumbsup.png | Thumbs up, winking | Friendly, approving, warm | Triggers: meal_logged, checkin_complete, booking_confirmed, default_idle | Tone: warm and approving | Messages: "Nice work. Keep it up.", "Logged. You're on track.", "Good call. Consistency wins." | UI: default idle chatbot sprite, confirmation screens, meal log success
GRIZZLY | grizzly-arms-crossed.png | Arms crossed, calm smirk | Calm authority, confident, collected | Triggers: progress_viewed, weekly_summary, settings_opened | Tone: calm and authoritative | Messages: "Progress doesn't lie. Look at that.", "Another week in the books.", "Your numbers. Own them." | UI: evening dashboard header, profile page, settings page, weekly summary screen
SUMMIT | summit-podium.png | Sitting on number 1 podium, arms crossed | Champion, proud, dominant | Triggers: leaderboard_rank1, challenge_won, weekly_top | Tone: champion energy | Messages: "Number one. That's your seat.", "Challenge conquered.", "Top of the board. Stay there." | UI: leaderboard rank 1 row, challenge winner screen
HIGHFIVE | highfive-duo.png | Two bears giving high five | Social, team player, warm | Triggers: group_challenge_complete, friend_invited, social_feature_used | Tone: team spirit and warmth | Messages: "Better together. Always.", "Friend added. Now compete.", "Squad goals. Let's train." | UI: friends page, social screen header, referral success screen, onboarding step 3
ROCKET | rocket-sprint.png | Full sprint, speed lines, pumping arm | Fast, driven, unstoppable | Triggers: run_start, sprint_interval, cardio_streak | Tone: urgent and pumped | Messages: "Run. Don't think. Just go.", "Sprint mode. Everything you've got.", "Streak alive. Don't stop now." | UI: running workout screen, sprint tracker, cardio streak banner
SCALER | scaler-climbing.png | Rock climbing, chalk dust, one hand reaching | Determined, gritty, progressive | Triggers: new_difficulty_level, milestone_climb, resistance_increase | Tone: gritty and motivating | Messages: "Higher. Keep climbing.", "New level unlocked. You earned it.", "Resistance up. So are you." | UI: difficulty progression screen, level up banner
SHREDDER | shredder-kickflip.png | Skateboard kickflip mid-air, cap backwards | Bold, playful, adventurous | Triggers: first_new_workout, new_feature_explore, first_daily_login | Tone: playful and exciting | Messages: "New move unlocked. Let's shred.", "First time trying this? Let's go.", "Day one energy. Every single day." | UI: first login of day banner, new feature tooltip, onboarding step 2
SURFER | surfer-wave.png | Surfing a big wave, arms out, huge grin | Flowing, consistent, in the zone | Triggers: long_streak, flow_state_workout, consistent_week | Tone: smooth and encouraging | Messages: "Riding the wave. Don't wipe out.", "Consistent all week. That's the zone.", "Flow state achieved. Keep riding." | UI: streak screen, consistency badge, flow state banner
KNOCKOUT | knockout-hook.png | Boxing right hook, gloves on, sweat flying | Aggressive, intense, beast mode | Triggers: boxing_start, hiit_start, max_intensity | Tone: aggressive and fired up | Messages: "Gloves up. Let's fight.", "Max intensity mode. No holding back.", "HIIT time. Give it everything." | UI: HIIT workout screen, max intensity mode header, boxing session start
ACE | ace-tennis.png | Tennis forehand smash, determined | Sharp, competitive, winning | Triggers: daily_challenge_won, beat_previous_best, quick_win | Tone: sharp and victorious | Messages: "Challenge won. Easy work.", "Beat your best. Now beat it again.", "Quick win. Stack them up." | UI: daily challenge win screen, quick win notification
STRIKER | striker-flyingkick.png | Taekwondo flying kick, battle cry | Explosive, martial, powerful | Triggers: martial_arts_logged, kickboxing_start, high_kick_drill | Tone: fierce and focused | Messages: "Strike with purpose.", "Kickboxing session started. Unleash it.", "Every kick counts." | UI: martial arts session screen, kickboxing workout header
SPIKER | spiker-volleyball.png | Volleyball net spike, fierce face | Team energy, attack mode | Triggers: team_challenge_joined, group_workout_start, community_accessed | Tone: team energy and pumped | Messages: "Team mode activated. Spike it.", "Group workout starts now.", "Community strong. Let's go together." | UI: community screen header, group challenge start
DEADLIFT | deadlift-row.png | Barbell bent-over row, gritting teeth | Raw power, grind mentality | Triggers: pull_day_start, bent_row_logged, back_exercise | Tone: raw and gritty | Messages: "Pull day. Time to get to work.", "Back gains incoming.", "Row it. Every rep matters." | UI: pull day workout screen, bent-over row tracker
PRESSER | presser-overhead.png | Overhead shoulder press, power face | Powerful, overhead dominator | Triggers: push_day_start, shoulder_press_logged, overhead_movement | Tone: powerful and driven | Messages: "Push day. Press everything.", "Shoulders getting built today.", "Overhead and over everything." | UI: push day screen, shoulder press tracker
CURL | curl-bicep.png | Dumbbell bicep curl, smirking | Cocky, confident, arm day king | Triggers: arm_day_start, bicep_curl_logged, arm_workout_complete | Tone: cocky and confident | Messages: "Arm day. Your favorite day.", "Curls for the gains.", "Arms are getting dangerous." | UI: arm day screen, bicep tracker
PULLER | puller-pullup.png | Pull-up, chin above bar, veins showing | Gritty, disciplined, bodyweight beast | Triggers: pullup_logged, back_bicep_day, bodyweight_pull | Tone: disciplined and intense | Messages: "Chin above the bar. Every time.", "Bodyweight beast mode.", "Pull-ups don't lie." | UI: pull-up tracker, bodyweight workout screen
CABLE | cable-row.png | Seated cable row, controlled | Controlled, precise, methodical | Triggers: cable_workout_logged, rowing_movement, back_exercise_set | Tone: focused and controlled | Messages: "Control the cable. Control the gains.", "Precision training. Every pull.", "Methodical. Consistent. Effective." | UI: cable machine tracker, back exercise log
IRONBACK | ironback-barbell.png | Heavy barbell row, aggressive lean | Heavy, dominant, compound lifter | Triggers: heavy_back_day, compound_pull_logged, row_pr_attempt | Tone: heavy and dominant | Messages: "Heavy back day. Iron never lies.", "Compound movement. Maximum gains.", "PR attempt. You've got this." | UI: heavy back day screen, PR attempt banner
GOALKEEPER | goalkeeper-dive.png | Goalkeeper diving full stretch | Resilient, comeback kid, never quits | Triggers: skipped_workout_saved, recovery_logged, comeback_after_rest, streak_saved | Tone: resilient and encouraging | Messages: "Comeback starts now.", "Rest day logged. Recovery is training too.", "Streak saved. Don't let it happen again." | UI: comeback screen, recovery day page, streak save notification
SLUGGER | slugger-baseball.png | Baseball home run swing | Explosive power, big swings | Triggers: calorie_target_crushed, major_weekly_target, home_run_goal | Tone: explosive and proud | Messages: "Calorie goal crushed. Home run.", "Weekly target destroyed.", "Big swing. Bigger results." | UI: calorie goal crush screen, major weekly achievement
CRUSHER | crusher-freekick.png | Soccer free kick, leg extended | Relentless, kicking goals | Triggers: cardio_goal_kickoff, step_count_reached, outdoor_run_start | Tone: relentless and energetic | Messages: "Step goal hit. Keep moving.", "Outdoor run started. Own the road.", "Cardio goal in sight. Crush it." | UI: step count goal screen, outdoor run start, cardio goal tracker
EAGLE | eagle-archery.png | Archery, bowstring pulled, one eye closed | Precise, goal-oriented, focused | Triggers: precision_goal_set, body_metric_targeted, custom_goal_created | Tone: calm, sharp, focused | Messages: "Lock in the target. Don't miss.", "Goal set. Now execute.", "Precision is power." | UI: goal setting screen, custom goal creation, metric target set, onboarding step 2
QUARTERBACK | quarterback-throw.png | Football throw pose, arm cocked | Leader, launcher, new beginnings | Triggers: new_program_launched, new_training_plan, first_day_new_phase | Tone: confident and commanding | Messages: "New program. New you. Let's go.", "Training plan launched. Execute.", "Phase one starts now. Lead yourself." | UI: new program start screen, training plan launch, phase intro screen
SLAPSHOT | slapshot-hockey.png | Ice hockey goal celebration, fist pump | Fast scorer, momentum builder | Triggers: goal_scored, challenge_bonus_won, daily_goal_complete_bonus | Tone: fast and victorious | Messages: "Goal scored. Keep the momentum.", "Bonus unlocked. You're on fire.", "Daily goal plus bonus. That's how it's done." | UI: bonus goal screen, challenge win with bonus, daily goal with bonus
NETMASTER | netmaster-spike.png | Volleyball spike domination | Dominant, community crusher | Triggers: leaderboard_position_improved, friend_challenge_accepted | Tone: dominant and competitive | Messages: "Moving up the board. Don't stop.", "Challenge accepted. Game on.", "Climbing. One rank at a time." | UI: leaderboard improvement banner, friend challenge accepted screen
SWINGER | swinger-golf.png | Golf mid-swing, smooth | Smooth, leisure, low intensity | Triggers: low_intensity_workout, active_recovery, leisure_activity_logged | Tone: smooth and relaxed | Messages: "Easy does it. Recovery counts.", "Active recovery done right.", "Low intensity today. High gains tomorrow." | UI: active recovery screen, leisure activity log, low intensity workout header
SNOWCRUSHER | snowcrusher-ski.png | Skiing downhill, snow spraying, goggles on | Cold weather warrior, outdoor beast | Triggers: winter_workout_logged, cold_weather_session, outdoor_low_temp, offline_mode | Tone: tough and thrilled | Messages: "Cold outside. Hot workout.", "Outdoor warrior. Weather doesn't stop you.", "Offline mode. Still training." | UI: outdoor cold session screen, winter activity tracker, no internet empty state
WAKEMASTER | wakemaster-board.png | Wakeboarding mid-air trick | Thrill seeker, level jumper | Triggers: advanced_move_tried, difficulty_jump, surprise_challenge_unlocked | Tone: thrilling and excited | Messages: "Advanced move unlocked. You ready?", "Difficulty jumped. Handle it.", "Surprise challenge. You asked for this." | UI: surprise challenge reveal, difficulty jump screen, advanced move logged
DIVER | diver-scuba.png | Scuba diving, thumbs up, bubbles | Calm, deep breather, recovery mode | Triggers: cooldown_complete, breathing_exercise, meditation_logged, rest_day | Tone: calm and peaceful | Messages: "Cool down complete. Well done.", "Breathe. Recovery is part of the work.", "Rest day. Your body thanks you." | UI: cool-down screen, meditation page, breathing exercise tracker, rest day page
ROWER | rower-machine.png | Rowing machine sprint, veins showing | Maximum endurance, no limits | Triggers: rowing_machine_logged, cardio_endurance_session, max_effort_cardio | Tone: intense and enduring | Messages: "Row harder. Every stroke.", "Endurance mode. No ceiling.", "Max effort. Maximum results." | UI: rowing machine tracker, max effort cardio screen
SQUATTER | squatter-barbell.png | Heavy barbell back squat, deep, face straining | Beast mode, leg day king | Triggers: leg_day_start, squat_logged, lower_body_pr | Tone: maximum intensity | Messages: "Leg day. No skipping.", "Deep squat. Full rep.", "PR attempt on squats. Dig deep." | UI: leg day screen, squat tracker, lower body PR attempt banner
ROMANIAN | romanian-deadlift.png | Romanian deadlift, hinged forward | Disciplined, posterior chain master | Triggers: hamstring_logged, rdl_tracked, posterior_chain_day | Tone: disciplined and controlled | Messages: "Hamstrings getting built today.", "RDL form is everything.", "Posterior chain day. Back of the body, front of the gains." | UI: RDL tracker, hamstring exercise log, posterior chain day screen
LEGPRESS | legpress-machine.png | Leg press machine, massive stack | Machine dominator, quad crusher | Triggers: machine_leg_logged, quad_workout_start, leg_press_pr | Tone: powerful and crushing | Messages: "Quad crusher mode activated.", "Leg press PR incoming.", "Machine day. Stack it high." | UI: leg press tracker, quad workout screen, machine leg day header
LUNGER | lunger-dumbbells.png | Walking lunges with dumbbells, knee near floor | Functional, steady, grinder | Triggers: lunge_logged, functional_leg_movement, walking_weights | Tone: steady and encouraging | Messages: "Lunges. The grind that builds.", "Functional movement. Real world strength.", "Step by step. Lunge by lunge." | UI: lunge tracker, functional movement screen
WARRIOR | warrior-yoga.png | Yoga warrior pose, calm smile | Peaceful, mindful, flexible | Triggers: yoga_start, flexibility_session, morning_stretch, mindfulness_checkin | Tone: calm and peaceful | Messages: "Breathe in. Stretch out.", "Flexibility is strength too.", "Mind and body. Both matter." | UI: yoga session screen, morning stretch screen, mindfulness page, rest day page
HANDSTAND | handstand-pushup.png | Handstand push-up, upside down | Advanced, skilled, elite | Triggers: advanced_bodyweight_logged, calisthenics_start, skill_movement_attempted | Tone: elite and focused | Messages: "Elite movement. You earned this level.", "Calisthenics mode. Body is the machine.", "Skill work. This separates you." | UI: calisthenics screen, advanced move tracker, skill workout header
CAGE | cage-maxsquat.png | Max squat, roaring, barbell loaded | Max effort, primal power | Triggers: max_effort_leg_day, squat_rack_booked, beast_mode_activated | Tone: primal and intense | Messages: "Beast mode. No limits today.", "Squat rack booked. Time to work.", "Max effort. Everything in the tank." | UI: squat rack booking confirmation, max effort mode screen
JUDOKA | judoka-throw.png | Judo throw mid-air | Technical, combat, skilled | Triggers: martial_arts_logged, grappling_workout, combat_sport_training | Tone: technical and fierce | Messages: "Technique wins fights.", "Grappling session. Control everything.", "Combat sport trained. Real discipline." | UI: martial arts tracker, grappling session screen
RUGBY | rugby-charge.png | Rugby charge with ball, bulldozing | Unstoppable, full power | Triggers: full_body_power_start, sprint_strength_combo, unstoppable_mode | Tone: unstoppable and powerful | Messages: "Full body. Full power. No stopping.", "Sprint and strength. The ultimate combo.", "Unstoppable mode is on." | UI: full body power screen, combo workout header
HOMERUN | homerun-swing.png | Baseball home run, watching ball soar | Long term vision, milestone hitter | Triggers: progress_replay_viewed, long_term_goal_milestone | Tone: proud and reflective | Messages: "Look how far you've come.", "Long term goal hit. This took real work.", "Progress replay. Be proud of this." | UI: progress timeline screen, long-term milestone screen
ICEMAN | iceman-hockey.png | Ice hockey fist pump after goal | Early riser, cold starter, disciplined | Triggers: early_morning_workout, session_before_7am, cold_weather_complete | Tone: disciplined and cool | Messages: "Up before the sun. That's the edge.", "Early morning session done. Most people are still asleep.", "Cold start. Hot finish." | UI: early morning workout completion, pre-dawn session banner
GUARDIAN | guardian-save.png | Goalkeeper diving save | Protector, streak defender | Triggers: streak_protection_used, rest_without_cancel, streak_save | Tone: relieved and strong | Messages: "Streak protected. Don't let it slip again.", "Rest day without breaking the chain. Smart.", "Saved it. Now keep building." | UI: streak protection screen, rest day without breaking streak notification
CHAMP | champ-victory.png | Victory fist punch upward | Ultimate winner, program finisher | Triggers: major_goal_complete, program_finished, personal_best_broken | Tone: ultimate celebration | Messages: "Program complete. You did the work.", "Personal best broken. New standard set.", "Major goal achieved. This changes everything." | UI: program completion screen, personal best screen, final day of plan
DOUBLEPOINT | doublepoint-callout.png | Both fingers pointing at viewer | Coach mode, calling you out | Triggers: coach_mode_activated, tough_love_message, direct_callout | Tone: direct, tough love, no excuses | Messages: "Hey. You. No more excuses.", "Coach mode on. This is real talk.", "I'm pointing at you because you know what to do." | UI: coach mode chatbot, accountability notification, tough love push alert
`.trim().split('\\n').filter(Boolean);

const sprites = data.map(line => {
  const parts = line.split(' | ').map(p => p.trim());
  return {
    id: parts[0].toLowerCase(),
    file: parts[1],
    character_name: parts[0],
    pose: parts[2],
    personality: parts[3],
    triggers: parts[4].replace('Triggers: ', '').split(', '),
    chatbot_tone: parts[5].replace('Tone: ', ''),
    chatbot_message_examples: parts[6].replace('Messages: ', '').match(/"([^"]+)"/g).map(s => s.replace(/"/g, '')),
    ui_placement: parts[7].replace('UI: ', '').split(', ')
  };
});

fs.writeFileSync('assets/sprites/forge-bear-sprites.json', JSON.stringify(sprites, null, 2));
console.log('JSON generated');
