import { StyleSheet } from 'react-native';

export const useStyles = (T: any, isDark: boolean) =>
  StyleSheet.create({
    cardContainer: {
      flex: 1,
      minHeight: 520,
      backgroundColor: T.colors.bg0,
      position: 'relative',
      overflow: 'hidden',
    },
    blurTint: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: isDark ? 'rgba(10, 10, 14, 0.65)' : 'rgba(245, 245, 247, 0.65)',
    },
    imageContainer: {
      ...StyleSheet.absoluteFillObject,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      backgroundColor: 'transparent',
    },
    foregroundImage: {
      width: '100%',
      height: '100%',
    },
    previewBtnWrapper: {
      position: 'absolute',
      bottom: 40,
      alignSelf: 'center',
    },
    previewBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: isDark ? 'rgba(30, 30, 36, 0.8)' : 'rgba(255, 255, 255, 0.8)',
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: T.colors.b1,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 5,
    },
    previewBtnText: {
      color: T.colors.t1,
      fontSize: 13,
      fontWeight: '700',
    },
    brandOverlay: {
      position: 'absolute',
      top: 61,
      right: 20,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? 'rgba(15, 15, 18, 0.75)' : 'rgba(255, 255, 255, 0.75)',
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 12,
      borderWidth: 0.5,
      borderColor: T.colors.b1,
    },
    brandText: {
      color: T.colors.t1,
      fontSize: 9,
      fontWeight: '700',
      letterSpacing: 0.5,
      marginLeft: 4,
      textTransform: 'uppercase',
    },
    statsPanel: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: isDark ? 'rgba(15, 15, 20, 0.92)' : 'rgba(255, 255, 255, 0.92)',
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      borderTopWidth: 1,
      borderTopColor: T.colors.b1,
      paddingTop: 20,
      paddingBottom: 24,
      paddingHorizontal: 22,
    },
    workoutNotes: {
      fontSize: 20,
      fontWeight: '800',
      color: T.colors.t1,
      textAlign: 'center',
      marginBottom: 3,
    },
    workoutDate: {
      fontSize: 12,
      fontWeight: '500',
      color: T.colors.t2,
      textAlign: 'center',
      marginBottom: 18,
    },
    statsGrid: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 20,
      gap: 10,
    },
    statBox: {
      flex: 1,
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.03)' : 'rgba(0, 0, 0, 0.03)',
      borderWidth: 0.5,
      borderColor: isDark ? 'rgba(255, 255, 255, 0.05)' : 'rgba(0, 0, 0, 0.05)',
      borderRadius: 14,
      paddingVertical: 12,
      paddingHorizontal: 8,
      alignItems: 'center',
    },
    statLabel: {
      fontSize: 9,
      fontWeight: '700',
      color: T.colors.t2,
      letterSpacing: 0.8,
      marginBottom: 4,
    },
    statValue: {
      fontSize: 16,
      fontWeight: '800',
      color: T.colors.t1,
    },
    actionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
    },
    actionBtnPrimary: {
      flex: 1,
      backgroundColor: T.colors.forge || '#E2F952',
      borderRadius: 14,
      height: 44,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    btnTextPrimary: {
      color: isDark ? '#000' : '#FFF',
      fontSize: 13,
      fontWeight: '700',
    },
    actionBtnSecondary: {
      flex: 1,
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.05)' : 'rgba(0, 0, 0, 0.05)',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255, 255, 255, 0.08)' : 'rgba(0, 0, 0, 0.08)',
      borderRadius: 14,
      height: 44,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    btnTextSecondary: {
      color: T.colors.t1,
      fontSize: 13,
      fontWeight: '600',
    },
    selectorContainer: {
      marginBottom: 20,
      width: '100%',
    },
    selectorLabel: {
      fontSize: 10,
      fontWeight: '800',
      color: T.colors.t2,
      letterSpacing: 1,
      textTransform: 'uppercase',
      marginBottom: 10,
      textAlign: 'center',
    },
    selectorRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 12,
    },
    selectorPill: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.04)' : 'rgba(0, 0, 0, 0.04)',
      borderWidth: 1,
      borderColor: T.colors.b1,
      borderRadius: 18,
      paddingVertical: 8,
      paddingHorizontal: 16,
    },
    selectorPillActive: {
      borderColor: T.colors.forge,
      backgroundColor: isDark ? 'rgba(255, 92, 46, 0.1)' : 'rgba(255, 92, 46, 0.06)',
    },
    colorDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      marginRight: 6,
    },
    selectorPillText: {
      fontSize: 12,
      fontWeight: '600',
      color: T.colors.t2,
    },
    selectorPillTextActive: {
      color: T.colors.t1,
      fontWeight: '700',
    },
    liveStickerOverlay: {
      position: 'absolute',
      bottom: 28,
      left: 24,
      right: 24,
      backgroundColor: 'transparent',
    },
    liveHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    liveShoeIcon: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    liveBrandText: {
      fontSize: 22,
      fontWeight: '900',
      fontStyle: 'italic',
      letterSpacing: 1,
      textShadowColor: 'rgba(0, 0, 0, 0.35)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    liveNotes: {
      fontSize: 32,
      fontWeight: '900',
      marginBottom: 24,
      textShadowColor: 'rgba(0, 0, 0, 0.4)',
      textShadowOffset: { width: 0, height: 1.5 },
      textShadowRadius: 3,
    },
    liveGrid: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    liveColumn: {
      flex: 1,
    },
    liveStatBox: {
      alignItems: 'flex-start',
    },
    liveStatLbl: {
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 4,
      textShadowColor: 'rgba(0, 0, 0, 0.3)',
      textShadowOffset: { width: 0, height: 0.5 },
      textShadowRadius: 1.5,
    },
    liveStatVal: {
      fontSize: 44,
      fontWeight: '900',
      lineHeight: 48,
      textShadowColor: 'rgba(0, 0, 0, 0.4)',
      textShadowOffset: { width: 0, height: 1.5 },
      textShadowRadius: 3,
    },
    liveStatUnit: {
      fontSize: 18,
      fontWeight: '900',
      marginTop: 2,
      textShadowColor: 'rgba(0, 0, 0, 0.3)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
  });
